### ISSUE TITLE
roboteam_ai crashes randomly 

### ISSUE THREAD

**Issue by rttwente** [RoboTeamTwente/roboteam_ai#810] opened 2020-02-22 18:46 UTC
**Describe the bug**
While running grSim, roboteam_world, and roboteam_ai, it can happen that roboteam_ai suddenly gives a segmentation fault. Sometimes it happens after 15 minutes, sometimes after 30 minutes.

**To Reproduce**
1. Start grSim, roboteam_world. Start roboteam_ai in debugger mode.
2. Do nothing for a long time
3. Possibly observe a crash. Last time, the debugger pointed to an error in Visualizer::drawRobots. However, I couldn't pinpoint what caused the crash.

**Comment by mrlukasbos** [comment] 2020-02-24 14:52
Ah i noticed this issue in the 'fix iomanager' PR. Thought it was my fault. It is fixed over there. the problem is that the interface runs in a different thread and is slow sometimes with drawing the robots on screen. The crash happens when the robot object is removed from memory while the interface is still trying to draw it. 

Note: the fix there is not elegant: it increases the history size with factor 10 to keep the robots alive 10 times longer.... 

fixed in #802

**Closed as completed** 2020-03-02 21:46 UTC
Labels: bug, high priority
